pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://172.31.36.8:9000'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -la'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube-server') {
                    sh '''
                        /opt/sonar-scanner/bin/sonar-scanner \
                          -Dsonar.projectKey=demo-app \
                          -Dsonar.sources=. \
                          -Dsonar.host.url=$SONAR_HOST_URL
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

       stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image --severity CRITICAL --exit-code 1 nginx:stable-alpine
                '''
            }
        }
	stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-creds', variable: 'KUBECONFIG')]) {
                    sh '''
                        kubectl set image deployment/demo-app nginx=nginx:stable-alpine -n demo-app --kubeconfig=$KUBECONFIG
                        kubectl rollout status deployment/demo-app -n demo-app --kubeconfig=$KUBECONFIG
                    '''
                }
            }
        }
    }
}