pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://172.31.36.8:9000'
        IMAGE_NAME = 'eldho10/capstone3-demo-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -la'
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('sonarqube-server') {
                    sh '''
                        /opt/sonar-scanner/bin/sonar-scanner \
                          -Dsonar.projectKey=demo-app \
                          -Dsonar.sources=. \
                          -Dsonar.host.url=$SONAR_HOST_URL
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build -t $IMAGE_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Image Scan') {
            steps {
                sh '''
                    trivy image --severity CRITICAL --exit-code 1 $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }

        stage('Push Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-creds', variable: 'KUBECONFIG')]) {
                    sh '''
                        kubectl set image deployment/demo-app nginx=$IMAGE_NAME:$IMAGE_TAG -n demo-app --kubeconfig=$KUBECONFIG
                    '''
                }
            }
        }

        stage('Rollout Verification') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-creds', variable: 'KUBECONFIG')]) {
                    sh '''
                        kubectl rollout status deployment/demo-app -n demo-app --kubeconfig=$KUBECONFIG
                    '''
                }
            }
        }
    }
}